config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  post 'check_password', to: 'pages#check_password'
  get 'success', to: 'pages#success'
  get 'failure', to: 'pages#failure'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  validates :pin, presence: true, length: { is: 5 }

  # emulating a db cause no db neede for this challenge
  def self.data 
        {
          info_text: " Sie können sich nun in den Versorgungsvertrag einschreiben.
                        Bitte geben Sie zuerst Ihren persönlichen PIN ein (diesen haben Sie
                        per SMS erhalten) und bestätigen mit „Anmelden“.
                        Anschließend erhalten Sie alle Informationen zum 
                        Versorgungsvertrag, den Therapieinhalten und die 
                        Teilnahmebedingungen.",
          dsec:  "Datenschutzbestimmungen",
          usage: "Nutzungsbedingungen",
          cb_text:  "Mit Eingabe des PINs und der Anmeldung bestätige ich, dass ich die 
                      x und x des Sanakey Portals gelesen und akzeptiert habe.",
          usage_link: 'https://www.sanakey.de/wp-content/uploads/2019/06/Nutzungsbedingungen-Sanakey-Portal-2.0-I-Stand-Mai-2019-1.pdf',
          dsec_link: 'https://www.sanakey.de/wp-content/uploads/2020/03/Datenschutzbestimmung-Sanakey-Portal-Stand-Februar-2020-1.pdf',
          info_title: 'Zusammenfassung',
          title: 'Herzlich Willkommen auf dem Sanakey-Portal!',
          password_hint: 'Ihr PIN soll exakt 5 Zeichen lang sein!'

    }
  end

  def self.change_status(msg)
    self.data['status'] = msg
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @user = User.first
    @msg = 'no error yet'
    # @password ='1test'
  end
 
  def check_password
    if params[:pin] == User.first.pin
      redirect_to success_path 
    else 
      redirect_to failure_path 
    end
  end

  def success
  end

  def failure
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ClickDummy</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/failure.html.erb
<html>

<head>
  <link href="https://fonts.googleapis.com/css?family=Nunito+Sans:400,400i,700,900&display=swap" rel="stylesheet">
</head>
<style>
  body {
    text-align: center;
    padding: 40px 0;
    background: #EBF0F5;
  }

  h1 {
    color: red;
    font-family: "Nunito Sans", "Helvetica Neue", sans-serif;
    font-weight: 900;
    font-size: 40px;
    margin-bottom: 10px;
  }

  p {
    color: #404F5E;
    font-family: "Nunito Sans", "Helvetica Neue", sans-serif;
    font-size: 20px;
    margin: 0;
  }

  i {
    color: red;
    font-size: 100px;
    line-height: 200px;
    margin-left: -15px;
  }

  .card {
    background: white;
    padding: 60px;
    border-radius: 4px;
    box-shadow: 0 2px 3px #C8D0D8;
    display: inline-block;
    margin: 0 auto;
  }
</style>

<body>
  <div class="card">
    <div style="border-radius:200px; height:200px; width:200px; background: #F8FAF5; margin:0 auto;">
      <i class="checkmark">x</i>
    </div>
    <h1>Fehler</h1>
    <p>PIN falsch<br /> 
    </p>
  <%= link_to 'Nochmal versuchen?', root_path %>
  </div>
</body>

</html>

app/views/pages/home.html.erb
<div class="border-bottom">
  <div class="container justify-content-between align-items-center">
    <%= render 'shared/header' %>
  </div>
</div>
<div class="container justify-content-around align-items-center">
  <div class="row justify-content-center">
    <div class="col-sm col-lg-8 border p-3 form" >
      <h2><%= User.data[:title] %></h2>
      <%= render 'shared/form' %>
    </div>
    <div class="col-sm col-lg-4 hidden-sm">
      <h4 class="p-3"><%= User.data[:info_title] %></h4>
      <p class="p-3"><%= User.data[:info_text] %></p>
    </div>
  </div>
</div>
<div class="container justify-content-between align-items-center">
  <%= render 'shared/footer' %>
</div>
 

app/views/pages/success.html.erb
<html>

<head>
  <link href="https://fonts.googleapis.com/css?family=Nunito+Sans:400,400i,700,900&display=swap" rel="stylesheet">
</head>
<style>
  body {
    text-align: center;
    padding: 40px 0;
    background: #EBF0F5;
  }

  h1 {
    color: #88B04B;
    font-family: "Nunito Sans", "Helvetica Neue", sans-serif;
    font-weight: 900;
    font-size: 40px;
    margin-bottom: 10px;
  }

  p {
    color: #404F5E;
    font-family: "Nunito Sans", "Helvetica Neue", sans-serif;
    font-size: 20px;
    margin: 0;
  }

  i {
    color: #9ABC66;
    font-size: 100px;
    line-height: 200px;
    margin-left: -15px;
  }

  .card {
    background: white;
    padding: 60px;
    border-radius: 4px;
    box-shadow: 0 2px 3px #C8D0D8;
    display: inline-block;
    margin: 0 auto;
  }
</style>

<body>
  <div class="card">
    <div style="border-radius:200px; height:200px; width:200px; background: #F8FAF5; margin:0 auto;">
      <i class="checkmark">✓</i>
    </div>
    <h1>Success</h1>
    <p>Aktivierung Erfolreich<br /> 
    </p>
  </div>
</body>

</html>

app/views/shared/_acceptance.html.erb
    
    Mit Eingabe des PINs und der Anmeldung bestätige ich, dass ich die 
    <%= link_to User.data[:dsec], User.data[:dsec_link] , target: :_blank %> und <%= link_to User.data[:usage], User.data[:usage_link], target: :_blank %> des Sanakey Portals gelesen und akzeptiert habe.
    

app/views/shared/_footer.html.erb
<%= link_to User.data[:dsec], User.data[:dsec_link] , target: :_blank %>
<%= link_to User.data[:usage], User.data[:usage_link], target: :_blank %>

app/views/shared/_form.html.erb
<%= form_with url: check_password_path do |f| %>

  <div class="form-group form-check"> 
      <%= f.check_box :x, class: 'form-check-input round-border', id: 'cond_box', placeholder: 'pin eingeben', required: true %>
      <%= f.label :x, class: "form-check-label", for: 'cond_box' %>
      <%= render 'shared/acceptance', f:f, class:'inline' %>
      <br>
  </div>
  <div class="form-group">
    <%= f.label "PIN", for: 'pin'%> 
    <%= f.password_field :pin, hint: "Die PIN ist 5 Zeichen lang.", label: "geben Sie die PIN ein", error: "Error in PIN", class: 'form-control', id: 'pin', required: true, minlength: '5', maxlength: '5' %> 
    <div id="passwordHelpBlock" class="form-text">
      <%= User.data[:password_hint] %>
    </div>
    <br>
  </div>
  <div>
    <%# <%= f.submit "Anmelden", class: "btn btn-outline-primary" %> 
    <%= button_to 'Anmelden', success_path, class: 'btn btn-outline-primary'%>
  </div>
  <br>
  <% if User.data[:status] %>
    Fault: <%= User.data[:status] %>
  <% end %>

<% end %>


<%# <script>
  const passwordHint = document.querySelector('#passwordHelpBlock');
  const passwordField = document.querySelector('#pin')
  if(passwordField){
    passwordField.addEventListener('change', (event) => {
      if (event.target.value.length !== 5 ){
        passwordHint.innerHTML = "PIN ist nicht 5 Zeichen lang!"
      }
  })
  }
</script> %>

app/views/shared/_header.html.erb
  <%= link_to image_tag('https://test.sanakey-portal.de/assets/logo.png', class: 'logo'), 
  'https://test.sanakey-portal.de/registrierung'
   %>  
   